### ISSUE TITLE
Scanner 처리 문제로 인한 이슈

### ISSUE THREAD

**Issue by hyuunnn** [Java-Spring-Study/java-baseball-game#8]
게임 시작할 때 Scanner 객체 생성을 하고, 게임이 종료되었을 때 close하는 방법이 제일 좋은 방법입니다.
아래의 코드를 사용하면 start 메서드를 호출할 때마다 Scanner 객체를 생성하게 됩니다.
https://github.com/Java-Spring-Study/java-baseball-game/blob/3171420e89401d560c6c47b77e2171f22f652893/hyuunnn/src/main/java/com/hyuunnn/baseball/Baseball.java#L101-L113

인스턴스 변수와 constructor를 사용하여 해결하려고 했으나, 사진처럼 값을 입력하는 단계를 무시하고 예외가 발생합니다.
![image](https://user-images.githubusercontent.com/15611739/194499660-29d527c5-8144-41b1-8508-a3289e4e97bd.png)

효율적인 방법이 떠오르지 않아서, 다음 스터디 시간에 같이 해결해보면 좋을 것 같습니다..!

**Comment by shkisme** [comment]
`Main` 에서 `Scanner`를 아래와 같이 선언해주고,
``` java
  public static Scanner scanner = new Scanner(System.in);
  public static void main(String[] args) {
    Baseball baseball = new Baseball();
    baseball.run();
    scanner.close();
  }
````
 `Scanner`를 import해서 사용하는 것은 어떨까요?

오늘 스터디 때 한번 더 이야기 해봐요!

**Comment by hyuunnn** [comment]
https://itbeginner2020.tistory.com/23
nextInt()를 사용할 때 개행 문자를 가져오지 않아서 다음 nextLine()에서 엔터 처리가 되었네요. 
해결되었습니다 :) https://github.com/Java-Spring-Study/java-baseball-game/commit/8d56d3099bb4d499b7a9db98fedf4844c790c0df
